### ISSUE TITLE
TypeError: normalize() argument 2 must be str, not float 

### ISSUE THREAD

**Issue by DewiBrynJones** [MiniXC/phones#6]
I'm creating a PhoneCollection with the `drop_dialects` and `merge_same_language` flags both set to False in order to load as many languages as possible.

```
>>> from phones import PhoneCollection
>>> pc=PhoneCollection(drop_dialects=False,merge_same_language=False)
```

but I get an exception ...

```
>>> pc=PhoneCollection(drop_dialects=False,merge_same_language=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\phones\__init__.py", line 77, in __init__
    ].apply(lambda x: unicodedata.normalize("NFC", x))
  File "C:\Python310\lib\site-packages\pandas\core\series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "C:\Python310\lib\site-packages\pandas\core\apply.py", line 1088, in apply
    return self.apply_standard()
  File "C:\Python310\lib\site-packages\pandas\core\apply.py", line 1143, in apply_standard
    mapped = lib.map_infer(
  File "pandas\_libs\lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "C:\Python310\lib\site-packages\phones\__init__.py", line 77, in <lambda>
    ].apply(lambda x: unicodedata.normalize("NFC", x))
TypeError: normalize() argument 2 must be str, not float
```

I don't know if you've this in hand in #5,  but for now I can proceed with a function wrapping `unicodedata.normalize` in an exception handler

i.e.

```
        def normalize(x):
            try:
                return unicodedata.normalize("NFC", x)
            except:
                return x

        if self.source.allophone_column is not None:
            self.data[self.source.allophone_column] = self.data[
                self.source.allophone_column
            ].apply(lambda x: normalize(x))
```

Thanks for a really useful library!!

**Comment by MiniXC** [comment]
This should not happen anymore in 0.0.3, turns out there were some rogue NaN values. Thanks for pointing this out!
